variables:
  ACRConnection: 'g4sxJoO6VMx/xHRLY4P5=Q9vXvFsvByY'
  RepositoryName: 'ps_catalog_base'
  ACRName: 'testingintouch.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'r$(Build.SourceBranchName).n$(Build.BuildNumber).i$(Build.BuildId)'
  BuildAPI: 'False'
  BuildAngular: 'False'
  
trigger:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - 'apps/demo/*'
      - 'apps/api/*'

stages: 
- stage: 'Build'
  displayName: 'Build and push'
  jobs: 
  - job: base_image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          npm i

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          declare -A arr
                  for i in $(npx nx affected:apps --base=remotes/origin/main~1 --head=HEAD |  grep -E ' - (\w|-|\d|_)+'  | sed -E 's/ - / /g' ); do
                    arr[$i]=$i
                    echo $i
                  done

                  if [[ ${arr['api']} ]]; then echo "##vso[task.setvariable variable=BuildAPI;]True"; fi
                  if [[ ${arr['angular']} ]]; then echo "##vso[task.setvariable variable=BuildAngular;]True"; fi
                 
                  echo $BuildAPI
                  echo 'done'

      displayName: get affected apps
   

    # - task: Docker@2
    #   displayName: "Build and push base image to ACR"
    #   inputs:
    #     containerRegistry: 'test'
    #     repository: '$(RepositoryName)'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: '$(tag)'
   
  - job: 'API'
    dependsOn: base_image
    condition: and(succeeded(), eq( variables.BuildApi , 'True'))
    steps:  
      - bash: | 
          echo $(someVal)
