# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - 'demo/*'
      - 'api/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from '/' root folder."