variables:
  ACRConnection: 'g4sxJoO6VMx/xHRLY4P5=Q9vXvFsvByY'
  RepositoryName: 'ps_catalog_demo'
  ACRName: 'testingintouch.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/apps/demo/Dockerfile'
  tag: 'r$(Build.SourceBranchName).n$(Build.BuildNumber).i$(Build.BuildId)'


trigger:
  branches:
    include:
      # - main
      - release_demo/*
  paths:
    include:
      - 'apps/demo/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  task: Docker@2
  displayName: "Build and push base image to ACR"  
  inputs:
    containerRegistry: 'test'
    repository: '$(RepositoryName)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: '$(tag)'