variables:
  ACRConnection: 'g4sxJoO6VMx/xHRLY4P5=Q9vXvFsvByY'
  RepositoryName: 'ps_catalog_api'
  ACRName: 'testingintouch.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/apps/api/Dockerfile'
  tag: 'r$(Build.SourceBranchName).n$(Build.BuildNumber).i$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: 'Build'
  displayName: 'Build and push'
  jobs: 
  - job: api_build
    pool:
      vm: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: "Build and push base image to ACR"  
      inputs:
        containerRegistry: 'test'
        repository: '$(RepositoryName)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'