# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - main
      - release/*
  paths:
    include:
      - 'apps/api/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from 'api'"